### ISSUE TITLE
Commercial license

### ISSUE THREAD

**Issue by rl-ilasic** [mooijtech/go-pst#14]
ReversingLabs is interested in commercial license. Could you please let us know how to do that?

**Comment by mooijtech** [comment]
Hello,

You can contact me via email or phone:
- Email: info@mooijtech.com
- Phone (the Netherlands): +31 6 30 53 47 67

I will try calling ReversingLabs on Tuesday.

**Comment by mooijtech** [comment]
I see you have already sent me an email, I will reply to this.
Thank you for letting me know!
