### ISSUE TITLE
how to export every message to eml file?

### ISSUE THREAD

**Issue by Xwudao** [mooijtech/go-pst#18]
I want extract the pst file to .eml files

**Comment by mooijtech** [comment]
Hello,

You can create EML files using https://github.com/emersion/go-message

You need to loop through all go-pst messages (https://github.com/mooijtech/go-pst#usage) then construct the go-message per https://github.com/emersion/go-message/blob/master/mail/writer_test.go

I will make a repository to show you how it's done in the weekend if I can get it working.

Kind regards,
Marten Mooij








________________________________
From: kk ***@***.***>
Sent: Wednesday, June 22, 2022 11:25:49 AM
To: mooijtech/go-pst ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mooijtech/go-pst] how to export every message to eml file? (Issue #18)


I want extract the pst file to .eml files

**Comment by Xwudao** [comment]
@mooijtech thank you very much.

**Comment by mooijtech** [comment]
Hello @Xwudao,

Here is the first iteration: https://github.com/mooijtech/go-pst-export
Supports exporting PST files to EML files (with attachments).
I have tested it on the Enron dataset, which is included.

Feel free to reach out if you have any other questions.

Kind regards,
Marten Mooij

**Comment by Xwudao** [comment]
@mooijtech 

Thank you very much. I'll try it later

**Comment by Xwudao** [comment]
@mooijtech 

I found a problem, 

![image](https://user-images.githubusercontent.com/31327868/176143863-49ab80f4-ca46-4a8a-a6d4-2b60d0cffea2.png)

It does not parse HTML tags

**Comment by mooijtech** [comment]
Hello,

I replied via email but used Reply All instead of Reply To and my message didn't end up in the GitHub issue. My apologies if you were sent this message twice.

This is intended behavior as the export strategy prefers a HTML body over plaintext. HTML is allowed in an EML message.

I assume when you say "doesn't parse HTML tags" you mean you want the message body to be the plaintext version?

I can add an export context option to prefer plaintext over HTML (which can be passed with the command line flag "-plaintext" or programatically setting the ExportContext "isPreferPlaintext" to true).

Kind regards,
Marten Mooij
________________________________

**Comment by Xwudao** [comment]
> Hello @Xwudao,
> 
> I have updated go-pst-export per [mooijtech/go-pst-export@9912297](https://github.com/mooijtech/go-pst-export/commit/99122971cd27a21ab4bb158db5f098b7dc4c7ce0) to support the flag "-plaintext" which constructs the EML message body with **only plaintext**: `go run cmd/export.go -plaintext`
> 
> If you have any other suggestions, feel free to let me know.
> 
> Kind regards, Marten Mooij

Thank you. You are so kind.

**Comment by mooijtech** [comment]
Closed due to being solved.

**Comment by mooijtech** [comment]
Hello,

This is intended behavior as the export strategy prefers a HTML body over plaintext. HTML is allowed in an EML message.

I assume when you say "doesn't parse HTML tags" you mean you want the message body to be the plaintext version?

I can add an export context option to prefer plaintext over HTML (which can be passed with the command line flag "-plaintext" or programatically setting the ExportContext "isPreferPlaintext" to true).

Kind regards,
Marten Mooij


________________________________
